### ISSUE TITLE
Is it possible to concatenate mask strategies?

### ISSUE THREAD

**Issue by mf-lit** [TheSoftwareHouse/fogger#11]
For example:

I need to generate "National Insurance Numbers", these must match the pattern:
AB123456C

Faker doesn't have direct support for this, but I'm hoping I could do it by using three mask strategies and concatenating the results.

- Generate two random letters
- Generate six random digits
- Generate one random digit

Is this possible? Thanks.

**Comment by tsurowiec** [comment]
you can use `regexify` from faker with `[A-Z]{2}[0-9]{6}[A-Z]`

https://github.com/fzaninotto/Faker/blob/fb218ada627f7c750c6e0e41cae486d2db48e911/src/Faker/Provider/Base.php#L465

**Comment by mf-lit** [comment]
This worked perfectly. Thanks!
