### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by devantler** [TheSoftwareHouse/fogger#32]
Hey, 

I am looking for a tool like this, but I can see this tool has not had updates since 2019. Is it still being maintained? If not do anyone know a similar service that can:

- Copy data from one database to another
- Obfuscate personal data
- Be containerised with Docker
- Work with mSQL

**Comment by tsurowiec** [comment]
Hi Nikolai

Yes, the project is not being maintained anymore. It was a side project when there was no client in my company and as soon as the paying client emerged, we moved to profitable work. At the current state Fogger is able to copy from one database to the other with some basic obfuscations, but it has been tested only with open source databases like mysql and postgres. Have no experience with MSQL :(

Don’t know if there are similar tools doing the same thing.

**Comment by devantler** [comment]
@tsurowiec thanks for reaching out. That is a shame, the use case seemed promising in cases where seeding data is no longer a manageable solution to replicate the production environment, and I have not been able to find a similar tool. 

Best of luck,
Nikolai
